apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pdf-service.fullname" . }}-secret
  labels:
    {{- include "pdf-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  MINIO_ACCESS_KEY: {{ .Values.minio.rootUser | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.rootPassword | quote }}
  API_KEY: {{ .Values.app.apiKey | quote }}
  OPENAI_API_KEY: {{ .Values.llm.openaiApiKey | quote }}
