apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdf-service.fullname" . }}-mongodb-service
  labels:
    {{- include "pdf-service.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "pdf-service.fullname" . }}-mongodb
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
