---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pdf-service.fullname" . }}-postgres-pvc
  labels:
    {{- include "pdf-service.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pdf-service.fullname" . }}-postgres
  labels:
    {{- include "pdf-service.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "pdf-service.fullname" . }}-postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "pdf-service.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "pdf-service.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: [pg_isready, -U, {{ .Values.postgres.user }}, -d, {{ .Values.postgres.database }}]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ include "pdf-service.fullname" . }}-postgres-pvc
